/**
 * The ONLY icon gateway — Feather icons via react-feather, mirroring the
 * app's components/Icon.js rule. Import icons from here, never from
 * react-feather directly. No emojis anywhere.
 */
export {
  ArrowLeft,
  ArrowRight,
  Award,
  BarChart2,
  BookOpen,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Coffee,
  CreditCard,
  Edit3,
  Flag,
  Grid,
  HelpCircle,
  Home,
  Layers,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Menu,
  Monitor,
  RefreshCw,
  Shield,
  Smartphone,
  Star,
  Target,
  TrendingUp,
  Unlock,
  User,
  X,
  XCircle,
  Zap,
} from 'react-feather';
